In [4]:
import pandas as pd

df = pd.read_csv("data/main.tsv", sep="\t")
print(df.shape)
print(df["lang_id"].value_counts())
print(df["task_type"].value_counts())

(7740, 64)
lang_id
tur    1290
ita    1290
ukr    1290
nld    1290
vie    1290
ara    1290
Name: count, dtype: int64
task_type
ht     2580
pe1    2580
pe2    2580
Name: count, dtype: int64

In [10]:
df.describe()

,flores_id,src_len_chr,mt_len_chr,tgt_len_chr,src_len_wrd,mt_len_wrd,tgt_len_wrd,edit_time,k_total,k_letter,...,doc_id,time_s,time_m,time_h,time_per_char,time_per_word,key_per_char,words_per_hour,words_per_minute,per_subject_visit_order
count,7740.000000,7740.000000,5160.000000,7740.000000,7740.000000,5160.000000,7740.000000,7740.000000,7740.000000,7740.000000,...,7740.000000,7740.000000,7740.000000,7740.000000,7740.000000,7740.000000,7740.000000,7740.000000,7740.000000,7740.000000
mean,523.341860,129.716279,131.429651,135.602842,21.413953,21.543605,21.955556,120.680828,153.087080,78.901163,...,53.788372,121.763983,2.029400,0.033824,0.926113,5.612146,1.175613,2164.501612,36.075027,215.500000
std,298.337523,44.583964,48.472997,50.864199,7.272320,8.915556,9.292165,315.726175,167.964254,91.841378,...,30.795440,320.217703,5.336962,0.088949,2.127478,12.603252,1.123952,9392.010883,156.533515,124.137992
min,6.000000,35.000000,27.000000,28.000000,8.000000,5.000000,5.000000,0.359000,0.000000,0.000000,...,1.000000,0.359000,0.006000,0.000100,0.001800,0.011800,0.000000,6.764500,0.112700,1.000000
25%,262.000000,97.000000,96.000000,99.000000,16.000000,15.000000,15.000000,39.314000,47.000000,18.000000,...,27.000000,39.314000,0.655200,0.010900,0.346575,2.070225,0.389750,587.649700,9.794175,108.000000
50%,524.500000,124.000000,126.000000,130.000000,21.000000,20.000000,20.000000,72.325500,117.000000,56.000000,...,53.000000,72.348000,1.205800,0.020100,0.579300,3.498500,1.011950,1029.003650,17.150050,215.500000
75%,823.000000,155.000000,160.000000,164.000000,26.000000,26.000000,26.000000,131.213750,207.000000,117.000000,...,81.000000,131.375000,2.189575,0.036500,0.997125,6.126100,1.581725,1738.941400,28.982350,323.000000
max,1012.000000,327.000000,390.000000,399.000000,49.000000,70.000000,78.000000,18094.487000,4380.000000,2586.000000,...,107.000000,18094.487000,301.574800,5.026200,95.234100,532.190800,17.950800,305217.391300,5086.956500,430.000000

In [11]:
df.head(10)

,unit_id,flores_id,item_id,subject_id,task_type,translation_type,src_len_chr,mt_len_chr,tgt_len_chr,src_len_wrd,...,tgt_text,aligned_edit,src_tokens,src_annotations,mt_tokens,mt_annotations,tgt_tokens,tgt_annotations,src_wmt22_qe,mt_wmt22_qe
0,flores101-main-tur-1-ht-1,205,flores101-main-11,tur_t1,ht,ht,155,NaN,147,25,...,2010 depreminden sonra Haiti'ye giden BM arabu...,NaN,"['UN', 'peacekeepers', ',', 'whom', 'arrived',...","[{'lemma': 'UN', 'upos': 'PROPN', 'feats': 'Nu...",NaN,NaN,"['2010', 'depreminden', 'sonra', ""Haiti'ye"", '...","[{'lemma': '2010', 'upos': 'NUM', 'feats': 'Ca...",NaN,NaN
1,flores101-main-tur-1-ht-2,206,flores101-main-12,tur_t1,ht,ht,165,NaN,175,27,...,"Davaya göre, BM kampının doğru biçimde sterili...",NaN,"['According', 'to', 'the', 'lawsuit', ',', 'wa...","[{'lemma': 'accord', 'upos': 'VERB', 'feats': ...",NaN,NaN,"['Davaya', 'göre', ',', 'BM', 'kampının', 'doğ...","[{'lemma': 'dava', 'upos': 'NOUN', 'feats': 'C...",NaN,NaN
2,flores101-main-tur-1-ht-3,207,flores101-main-13,tur_t1,ht,ht,106,NaN,92,18,...,Bu ekip gelmeden önce Haiti'de 1800'lerden ber...,NaN,"['Prior', 'to', 'the', 'arrival', 'of', 'troop...","[{'lemma': 'prior', 'upos': 'ADJ', 'feats': 'D...",NaN,NaN,"['Bu', 'ekip', 'gelmeden', 'önce', ""Haiti'de"",...","[{'lemma': 'bu', 'upos': 'DET', 'feats': '', '...",NaN,NaN
3,flores101-main-tur-1-ht-4,208,flores101-main-14,tur_t1,ht,ht,176,NaN,216,24,...,Haiti'deki Institute for Justice and Democracy...,NaN,"['The', 'Haitian', 'Institute', 'for', 'Justic...","[{'lemma': 'the', 'upos': 'DET', 'feats': 'Def...",NaN,NaN,"[""Haiti'deki"", 'Institute', 'for', 'Justice', ...","[{'lemma': 'Haiti+ki', 'upos': 'PROPN+ADP', 'f...",NaN,NaN
4,flores101-main-tur-1-ht-5,209,flores101-main-15,tur_t1,ht,ht,105,NaN,135,17,...,BM'nin hastalık konusundaki uzmanlarından biri...,NaN,"['Danielle', 'Lantagne', ',', 'a', 'UN', 'expe...","[{'lemma': 'Danielle', 'upos': 'PROPN', 'feats...",NaN,NaN,"[""BM'nin"", 'hastalık', 'konusundaki', 'uzmanla...","[{'lemma': 'Bm', 'upos': 'NOUN', 'feats': 'Abb...",NaN,NaN
5,flores101-main-tur-10-ht-1,927,flores101-main-101,tur_t1,ht,ht,165,NaN,174,27,...,"Uçakla seyahat etmek, yaşı ve geçmişi fark etm...",NaN,"['Travelling', 'by', 'plane', 'can', 'be', 'a'...","[{'lemma': 'travel', 'upos': 'VERB', 'feats': ...",NaN,NaN,"['Uçakla', 'seyahat', 'etmek', ',', 'yaşı', 'v...","[{'lemma': 'uçak', 'upos': 'NOUN', 'feats': 'C...",NaN,NaN
6,flores101-main-tur-10-ht-2,928,flores101-main-102,tur_t1,ht,ht,137,NaN,113,26,...,Birçok insanın bazı şeylerden korkmasından vey...,NaN,"['It', 'is', 'not', 'something', 'to', 'be', '...","[{'lemma': 'it', 'upos': 'PRON', 'feats': 'Cas...",NaN,NaN,"['Birçok', 'insanın', 'bazı', 'şeylerden', 'ko...","[{'lemma': 'birçok', 'upos': 'DET', 'feats': '...",NaN,NaN
7,flores101-main-tur-10-ht-3,929,flores101-main-103,tur_t1,ht,ht,176,NaN,180,32,...,Uçağın işleyişini ve bir uçuş sırasında neler ...,NaN,"['For', 'some', ',', 'understanding', 'somethi...","[{'lemma': 'for', 'upos': 'ADP', 'feats': '', ...",NaN,NaN,"['Uçağın', 'işleyişini', 've', 'bir', 'uçuş', ...","[{'lemma': 'uçak', 'upos': 'NOUN', 'feats': 'C...",NaN,NaN
8,flores101-main-tur-100-pe1-1,894,flores101-main-1001,tur_t1,pe1,pe,124,126.0,128,21,...,"Yeniden giriş şoku, kültür şokundan daha erken...",REF: yeniden giriş şoku * kültür şokundan dah...,"['Re-entry', 'shock', 'comes', 'on', 'sooner',...","[{'lemma': 're-entry', 'upos': 'NOUN', 'feats'...","['Yeniden', 'giriş', 'şoku', 'kültür', 'şokund...","[{'lemma': 'yeniden', 'upos': 'ADV', 'feats': ...","['Yeniden', 'giriş', 'şoku', ',', 'kültür', 'ş...","[{'lemma': 'yeniden', 'upos': 'ADV', 'feats': ...","['OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK...","['OK', 'OK', 'OK', 'BAD', 'OK', 'OK', 'OK', 'O..."
9,flores101-main-tur-100-pe1-2,895,flores101-main-1002,tur_t1,pe1,pe,137,117.0,117,22,...,"Yeni kültüre kolayca uyum sağlayan gezginler, ...",REF: yeni kültüre kolayca uyum sağlayan gezgi...,"['Travellers', 'who', 'had', 'an', 'easy', 'ti...","[{'lemma': 'traveller', 'upos': 'NOUN', 'feats...","['Yeni', 'kültüre', 'kolayca', 'uyum', 'sağlay...","[{'lemma': 'yeni', 'upos': 'ADJ', 'feats': '',...","['Yeni', 'kültüre', 'kolayca', 'uyum', 'sağlay...","[{'lemma': 'yeni', 'upos': 'ADJ', 'feats': '',...","['OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK...","['OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK', 'OK..."

In [14]:
df_pe_only = df[df['translation_type']=='pe']
print(df_pe_only.shape)
print(df_pe_only["lang_id"].value_counts())
print(df_pe_only["task_type"].value_counts())

(5160, 64)
lang_id
tur    860
ita    860
ukr    860
nld    860
vie    860
ara    860
Name: count, dtype: int64
task_type
pe1    2580
pe2    2580
Name: count, dtype: int64

In [17]:
df_test_vi = df_pe_only[df_pe_only['lang_id']=='vie']
df_test_vi.describe()

,flores_id,src_len_chr,mt_len_chr,tgt_len_chr,src_len_wrd,mt_len_wrd,tgt_len_wrd,edit_time,k_total,k_letter,...,doc_id,time_s,time_m,time_h,time_per_char,time_per_word,key_per_char,words_per_hour,words_per_minute,per_subject_visit_order
count,860.000000,860.000000,860.000000,860.000000,860.000000,860.000000,860.000000,860.000000,860.000000,860.000000,...,860.000000,860.000000,860.000000,860.000000,860.000000,860.000000,860.000000,860.000000,860.000000,860.000000
mean,523.341860,129.716279,136.255814,139.603488,21.413953,30.250000,30.932558,192.948909,202.882558,75.897674,...,53.788372,192.948909,3.215817,0.053598,1.420810,8.632918,1.570633,1093.916282,18.231939,211.397674
std,298.491843,44.607025,48.175268,51.254868,7.276082,10.633116,11.241869,764.424130,159.088487,62.724846,...,30.811370,764.424130,12.740403,0.212339,4.671060,27.705274,1.107390,808.145820,13.469098,123.605205
min,6.000000,35.000000,39.000000,37.000000,8.000000,9.000000,9.000000,6.324000,0.000000,0.000000,...,1.000000,6.324000,0.105400,0.001800,0.074300,0.496900,0.000000,6.764500,0.112700,1.000000
25%,262.000000,97.000000,103.000000,104.750000,16.000000,23.000000,23.000000,48.163750,85.000000,32.000000,...,27.000000,48.163750,0.802725,0.013400,0.423875,2.442675,0.760875,537.711475,8.961850,103.000000
50%,524.500000,124.000000,129.500000,132.000000,21.000000,29.000000,30.000000,82.221000,160.000000,59.000000,...,53.000000,82.221000,1.370350,0.022850,0.655250,3.971050,1.395900,906.563150,15.109400,210.000000
75%,823.000000,155.000000,166.000000,170.250000,26.000000,37.000000,37.000000,148.206500,286.000000,100.000000,...,81.000000,148.206500,2.470125,0.041200,1.111650,6.695075,2.178650,1473.802125,24.563400,322.000000
max,1012.000000,327.000000,320.000000,349.000000,49.000000,70.000000,76.000000,18094.487000,1240.000000,433.000000,...,107.000000,18094.487000,301.574800,5.026200,95.234100,532.190800,8.241900,7244.371800,120.739500,430.000000